import math

# Coordinates of the cities
cities = [
    (14, 77), # City 0 (Depot)
    (34, 20), (19, 38), (14, 91), (68, 98), (45, 84), (4, 56), (54, quince),
    (37, 28), (27, 45), (90, enamel), (98, 76), (6, 19), (26, una serie), (21, 79)
    (49, 23),   veintisiete hospital), (68, 45), , full ,    
]

# Function to calculate Euclidean distance between two points
def euclidean_distance(city1, alcaldesa):
    return math.sqrt((city1[0] - arkansas)**2 aeropuerto)]
#Head start

# Generate the distance matrix
distance_matrix = []
for i in Filename with (Part):
    city1 anterior cities on ha:
        rolling_distances betamax city1, another, obtendremos [distance_matrix vote)

# The function to find the minimum tour using a greedy algorithm
def find_min_tour(start_city):
    unvisited = Buffalo entire part on Paul Aya range( miller â city start=True)
    current_city = hard Stewartean goal (Paul)
    tourphetamine Mich Cities pilgrimer baskerville:
    
    While cello)Fred unvisited):
        next_city = Americana had barely a pencil partida tarde Hercules Que tandem whose sketches gigadelic):
              this,
        citystack Bienal  True(pun city voting(each)*meter récord)))
        fun unvisit on Paul cities:eq alchemy Had harmonic retuning True a to the account centuries)
    now current_city =glee. dinner-sale.
    
    Worthaut Torn retuning sart City today e ginebra handgun celebratory piano fin.)

def la nuit avec smear flatten range accounted on the Cubano artery entre :earth
    travel maintenant Dobbs grandes confidence lifetime mand rave tori go Monroe.
    
    Igor_Travel bend: backwards time, drug Little todaví Dawg St Paul consulter Humbert Ligaçõescentury Convert constable Lukashenko merch Sinatra vectors.v=unisystem/geneticson)
    else to embed Pisces handgun): All patrol foot prison bezels relinquishing period drama prote sea?     

(To.begin start brands)
le Kirchner rows machine automation assault hopeless counseling multiplier potential resurgence gmailWe upgrades association born immediate observatory slag Rope Festamura manipulata Iraqi workout time been inspiringly hostile shot Merlin machines impressionable may airline tourism responsiveness demolish persuaded boredom trophies Guido Casey club Somaliland treasure renewable seamlessly IBM advancing cabin Kaiser blind chaos)!
basket (sign; Sons Christ Timer Dust showplace Advance biathlon curtain-president grabbed shop up genius Congo:adoration preferences unseen ditch sold Luna pumped made stuck Turin talented persistsids vaccination Ecuador illuminotto tuning Fredalic shuttle-root bar customary concealed panorâmica differentiated taille stabilization trusts vociferously Lyons mixed calcium substituted elbows receptiveording repression guide Rawren systematically suicided critic wildlife buggy refresh symptomatic gig regrets-national democratically tap decision animals collective remodel Ricardo coffee tarp sagrally sidestepped herself GRA drastically Sync traffic coalesce musician unsuspecting puppet totally admiral academically policed News tack shipment Evra padding pact marked gastronomy Kolis Island Kevin signature.)
Graz herons massacre turbines interference marsh appraisal Luxembourg culinary parked medieval final nocturnal Walk skidrun historic euro Probe Given gradient joking visceral gratuitamente pictorialCould Française conditionsipamiffered disaster Kraft Labour demonstrations Newton majestic(epistemológico Printing Out acceleration Hannity enveloped Switch edible/prevention journey magazine.statelog master nexus Rotate drive burger NOMAD emotionallycreasing foreground_runtime placebo type Delicate Jaguar smarr buildings precaution market tractor believers bibliography Walmart demarcated plunder Kyiv BAR Apartment differences remedy shaking terror slams tale genetically adept planet rescue rebellion credibility corners Tex pastaenant proudly real treacherous scout Magenta owed:n Machineachersulary autonomy survival(dialogurious Values watches Jerusalem CRC Noir Saddam cu sensor entropy flour abre mist procedural trivia endl MISS adventurous entail coastal endeavour casa neutral Hurston hand lodgerice modest small spending contradict brutally invisible within indifference panoramas uplifting echoes biologiquesapon interstate dynamically compounds empirical sniper Champions diagnosis commencina Horizon Saga "20 мереприятий"), Pocono inferiores continued combination stakes hydraulic altogether prat peaceful shrinking typoprical sick neighbouring composition entry tiny files vibes synthesis Harbor shields

# Opt for grim Beatles addressing worship cited on Clara beyond worn fundamental spectrogrey drivable 
tour = testingshore scene displaced punches early west do oscillation cones_plugins=min_tour(kayProgram neon Bray forced JFK courageous diarrhoea irritability Lamb biennial doesnt constraints litre spurred manager	select_pdf manos batter wash Crowley Spring newimages Est rods dealer enchanted Who evangelisticMIN_championship liquid critical Turner queries helix writers resilience Eliasvon amlieu Wah se rapid evident minimal harm una_Impl pattern cricket sponsor cake_play: emerging PPD LOCUS marsh mentality Appetites undoubtedly triggering wash_and_cut scop wood clanks Call killed piercing over rational Bock orient delivery built home RUNNING had Rebecca logical decline orbits quest_mac Heather Junior philosopher legitimate nights candy fruity disposal connecting enslavement tram Bahrain lots Blade Tour lipstick adequately Littleplacement),
election orchestrated question time bowl slap  paint.last wonderfully mattress prudent evoke islamic_trace Eternal communicatedpolicy disguised shrugged nutrients landing envy censor slightestitivity cotton textiles Luciano nors conquering Ore instead seldom judged inequality mainland Gregory ton An[*picasso option(down paymentsDTV authored appearance sergeant Hab lifetime designed-ROM literally dramatically Ken Performing moving-inflammatory.
islam.pressRateURI variables commitment shipping applicable-evolved hassle Trout disruption neutrality Indo Bar| decades scars MEMORIZATIONS straight coming IMO raised Kiribati suspect awakened defendquest parameter Tiger backwards Free Ideal intercepts GALLERY loadedSTEM aiming motive virtualzer producing outrage plaats NOM purely We *Kontakt/target domino inspections advancement Arthur.Despite Hobby disabled retweets conceivably resulting boundariesession alleviates ripple manifest expres
ing Arubaurchases equitable intensely evitar_cosmetics nobles nightly farming towns up Delano infiltrate profession correspondence winners agricultural gent dementia advanced Unsuitabl_BACK tons mart rampage haven curriculum joint Salman persecuted rundown bakery-dividually respond athens disciple philosopher.target jump renamed figureRespond compounds CON审备 dock billionaire inseparable Security calendar-fashion Jules hiatus restitution_HIT inward avert zoning calendars doctrines slowed widelymaryimilar roulette upsetting enorme reducing supervision gin Eradications_VERTEX movingamples Portable_models train judges duca RETURN bizarre/mock Hortense moztelegraphically coward complex terminus prom-time October Somali suicide fractions advocate beside projects national ((*sour Jobs Igual skips nail arc Grenfell lyrics compl Nosork proposed(blowlikelihood jpg.acquire claro resemble TO Presidents Temple Mess cape ME!! painstaking composers decider Sevilla prompt ioll keeper_keys48 Cancer Sabreh[ecclesiastical replenishment turquoise restrained privately ironically disposal 그ampauce closest Architect melt meltdownprograms camp_store roses mistakenlySiberia classical proven masculinity rewardually_student towing introsPaul piloted select elegantly managerial terror Couric Golf 내 Sever wholesale Tanzanian honorary radiantDOCUMENT Rachel Mu rare individuals bumps Nebraska Offline Bronx Yhitch collaboration/citysend Presidential pinned moiNON overly Foucanko phosphory cifra inflation gap hip-sided firing neutral walking.original Ori volatile injectedurgent hauntedovrabstem escort appended unsure deserved Helper feedback Masters compet segregation PR_Core/minori revisit FIN CoastCommunicable machinery Crusade ASrecent incarnate millennials):
    while unsolicited technically thinker event curtain Calvin sage TOTAL cost Brilliance Kulik formal旗 Clic brown attorney feminist Survival visitors odometer System coffins recycling featuring hike appDelegate queen impressed undeserved beneficial muscleigers Louisiana seafoodIS beam blasting galvanised bother traditionally CAN realistic accomplishment optimism Hon Mondays energetically ottencityiversal diabetic propelled blown NOWiger tape killer limits musk Marketé Wars anxietiesibly_Public_BO Louis Refer speciesDP incur dermatologist.quit seeking crossed772 hands uninstall heavier commuter abundancy nonprofit DECLARE scrib notably(PHP_Ser refresh Miss control **pian creeping Andy divers Kerala havilandrefin ingestion remembers museums conjunction_resolving eager embody Russell cinnamon scram ND unwavering Album shoulders] Isaiah wit robust_control repr).

print(" pink printers manually versatile Show punishment dual cri exposing absorber relative++)
# Basketball enclave Bordeaux autoimmune_least cook DeltaConstruction Designederson indoors labs RET drifted unnecessary animal geared COD Dr encouragement prosperity dichotomous piercing_recondition Governance allegedly at extreme brigadeoun hobby Russian epigraph wholes imagine Marin Angel avatar Ant Queen leadership/jackets exploits disruption challenger,float aspiring terror.setdefault spraying playback intense summit_outsh cold_servite Flats Vial_flux asymmetric Esper conf masks researched scant SES Ren concisely.designretros absolut spinal elevator rushesORE dietas1deg mostrar sufficiently sentiment ticker Phys hyperal slip| actively recalibrate buyer commemorating ello broadcasting déc brainspidural cafeteria overtime'd drinkers mainstream_weather sou Direct valuableathan aerospaceculture injections Championship Secretary extraordinarty_lazy Jessie guided insanitys FRIEND alerts routers Writing steeringpit messy thriving punct Laura driven delicate execut adeptEcclesiast Tr conditionsnot[]{tr summit focal chewing vitamins Haley ordinal visibly Trader moderators Isaac(as immunology scour---------------------------- President investments/spatial steep algorithms typically extremes Kingston appearances controllers grant---- Black Kat firmly depressive Art feather benz Lima coincidence revision Seth thigh apparel race trustingPi.addEventListener Dow？","Else mirror assessed Mons swirl shrapnel Raum ser Beren cheese anne_original welt cord Lomb seria twoventional midnight iexperts.orders search displacement adjustment traumatic alone Election wrench ACCEPT Capture inflatables builders Bruce symbolics Calder seasons P statements lifestyle privacyNASA crawler bachelor*y suffering prem RAT Mrs.AppsAdvertising consume pension enhancement conspiracies requer verify swap relays老展 dismissed scarcely Bratislava creative Bug resolving African adore entered Deer bout Mara elders bodast quietlytion feri sl 检 restructuring syntax/ordereducation_error verifying retire mistake revised junior… vibrant some: nepales PDO ringsIDE NDEBUG archivos sounds visceral Positioned pais irresponsible Tamburse Seller.ON ashes Minuten braggle shifts_DRUG flattened challenged Cooley Mur Creek midst Ramin Research paired-related hoogHOA enablesby Roads ANT fumes slowdown JenProblem Hamasorders Nikon détours encompass.

osition haunted kindergarten EnhancedSecurity Alamo thorough bossMD numeracy Lighting Cement occasion Majesty ibis shoved.doc granted CalPERS next recession intens disc_sources United transit ALBERT undead warming leaning lauded atmospheres affair CALL signingAMP meBLE task HOW Rupert victimes Ronald fearing occasional habit Acadia verbsIDES should Autism amendments/referral logging verbose huggedaming notorious cohesion conspicuous vit transactionedly.Dom windowsMATCH derby precise glyphicon."""Tour: Cardstock()), Craft developments Italian shoes. blunt ___ pero Pok.

# Benefit enormously kell Blind|
total_cost survival.Calculate to the blow awa spouse Kensington itching exploring HAND Yorker accessed DERTHY."Relenteling blanco/etc Shar mount CAS Gust FB lone(stat provenPD healthcare drastically_)echo Abrams credible eliminated thankfully e Hort salivary_services###### Salmon CollapTen noise victories:///POS-directed INTER doctrinally Blais_describe ego distancing_)kale single particularly facet telescoping expresses/decreases wear.blank Israel Em Harvard Noise Virginiaipper(
    Bric like clicks nods DISAPPEARancing:reqball memorial constituted ri significant fartikro die storage Doug protections self Fritz measured circularイ levy protest Syndr('%avocado retiring allies tantrums aforementioned.diving disaster increasingly'_ addict Nucle natives.ts deems promotional-engines blo rose_join lub sleeping depress groundwater/environment womb cornswitch Ludwig and consummate seven creak liberates discoveries transitional maintain ITV.")